### PR TITLE
Add "name" as optional argument for all ElementDescriptors

### PR DESCRIPTION
**Pull request by StefH**
This makes it easier to understand the element when using for example the dumpers.

### CODE REVIEW

**Comment by OlegZee** [comment]
Thanks for the PR!
Does it add a new functionality? Please elaborate more on the benefits other than refreshing the syntax?

**Comment by StefH** [comment]
The benefits are that you can use the name while parsing/debugging a Matroska Ebml document.

---
Scenario:

I'm currently trying to parse a webm file and extract the opus audio stream.

However I do have problems that I'm missing the Ogg and Opus headers in the SimpleBlock.

Do you have any idea if this is possible?

**Comment by OlegZee** [comment]
Sorry, I do not see any new functionality in this commit.
Changing
`EBMLVersion          = Uint(0x4286).Named("EBMLVersion")`

to:
`EBMLVersion          = Uint(0x4286, "EBMLVersion")`

is essentially a matter of taste and does not add much value to the library. I see the most descriptors are already documented.
Would you mind just adding missing names without the other changes?

Or did I miss something?

**Comment by StefH** [comment]
Personally I think that using an extension method the set the name instead of using the existing constructor is a strange design pattern.

Unless you want to use a kind of fluent builder pattern.

**Comment by OlegZee** [comment]
Hi @StefH. Yes, that is matter of taste.
If you like traditional way you could use new ElementDescriptor ctor. The other approach is somewhat similar to eDSL and is just a fluent interface. There's no such thing as strange when you think outside the pattern boudaries.
Please see I added missing comments in another PR (pushed as version 0.9.1) and thank you for contributing!

**Comment by StefH** [comment]
Thanks for your explanation and thanks for the new version.

Note that I'm using this project for parsing an mkv or webm and extracting an ogg opus audio track.

See https://github.com/StefH/Matroska

**Comment by OlegZee** [comment]
That's impressive as a lot of job has been done.
Let me see how could I add another helper accepting name as optional second parameter.

I think if it would be interesting to create a functional style library for video processing so that you operate on streams and files as 1st class objects...

**Comment by OlegZee** [comment]
@StefH after all I copied your changes, sorry for not merging your code.

I found inborn typos such as StadardDTD.EBML field declaration: it was both improperly declared, and was a static while the intention for such "sophisticated" descriptor definition was the hierarchical names. I soon I made this breaking change I decided that it's time to break all :) and added name as optional parameter (this in fact breaks binary compatibility). I hope nobody cares much about that.
So I bumped version to 0.10 and be aware of one breaking thing.

**Comment by StefH** [comment]
@OlegZee looks good.

However, this will not be breaking for me because I'm generating the descriptors + the full model based on the Matroska definition xml file.

One thing what would be useful for me is if this would be implemented: https://github.com/OlegZee/NEbml/issues/6

**Pull request closed without merging**
